Repository goreleaser/goreleaser-azure-devops-extension, pull requests merged in 2021-11, with the labels that each got.

#10 chore: fix license
  LICENSE
Labels: size/L

#11 chore: fix license
  README.md
Labels: size/XS

#12 fix: rename ext id
  .DS_Store
  .gitignore
  goreleaserTask/src/utils.js
  goreleaserTask/src/utils.ts
  vss-extension.json
Labels: size/S

#17 docs: add LICENSE to vss-extension.json
  README.md
  vss-extension.json
Labels: size/S

#18 feat: align repo more to other goreleaser orga repos
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/stale.yml
  .github/workflows/lock.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: size/L

#24 feat: create autodeploy of extension
  .github/workflows/ci.yaml
  package-lock.json
  package.json
  vss-extension.json
Labels: size/M

#27 feat: versioning
  .github/workflows/ci.yaml
  .release-it.json
  package-lock.json
  package.json
Labels: size/S

#28 feat: versioning
  .github/workflows/ci.yaml
  .release-it.json
  package.json
Labels: size/M

#29 feat: versioning
  .github/workflows/ci.yaml
  package.json
Labels: size/S

#30 feat: versioning
  package.json
Labels: size/XS

#31 feat: versioning
  package.json
Labels: size/XS

#32 feat: versioning
  .github/workflows/ci.yaml
  README.md
Labels: size/XS

#34 feat: set useUnknownInCatchVariables int tsconfig.json
  .gitignore
  goreleaserTask/src/index.d.ts
  goreleaserTask/src/index.js
  goreleaserTask/src/index.js.map
  goreleaserTask/src/utils.d.ts
  goreleaserTask/src/utils.js
  goreleaserTask/src/utils.js.map
  goreleaserTask/tsconfig.json
  tsconfig.json
Labels: size/L

#35 feat: sort order of version bump
  .github/workflows/ci.yaml
  package.json
Labels: size/S

#39 docs: change wording in the readme
  README.md
Labels: size/XS

#43 feat: add autoupload of dev version
  .github/workflows/ci.yaml
  goreleaserTask/task.json
  vss-extension.json
Labels: size/M

#44 feat: add autoupload of dev version
  package.json
Labels: size/XS

#45 feat: add autoupload of dev version
  .github/workflows/ci.yaml
Labels: size/XS

#46 Dev5
  .github/workflows/ci.yaml
  package.json
Labels: size/S

#47 chore: rename yml to yaml in c&p workflows
  .github/ISSUE_TEMPLATE/config.yaml
  .github/workflows/lock.yaml
Labels: size/XS

#48 Share
  .github/workflows/ci.yaml
  package.json
Labels: size/XS

#49 fix: remove $ on SHARE_WITH_DEV_ORGA in ci
  .github/workflows/ci.yaml
Labels: size/XS
